[
	{
		"key": "dbln",
		"value": "%7B%2261588112155761%22%3A%22ugKWrZYb%22%2C%2261588342577468%22%3A%225U0pwYax%22%7D",
		"domain": "facebook.com",
		"path": "/login/device-based/",
		"hostOnly": false,
		"creation": "2026-03-20T06:30:14.979Z",
		"lastAccessed": "2026-03-20T06:30:14.979Z"
	},
	{
		"key": "datr",
		"value": "7yO8aSL81uaRwQAzhrsrFE0s",
		"domain": "facebook.com",
		"path": "/",
		"hostOnly": false,
		"creation": "2026-03-20T06:30:14.979Z",
		"lastAccessed": "2026-03-20T06:30:14.979Z"
	},
	{
		"key": "sb",
		"value": "7yO8aVlZOwIDeS4IAWM3Vjp3",
		"domain": "facebook.com",
		"path": "/",
		"hostOnly": false,
		"creation": "2026-03-20T06:30:14.979Z",
		"lastAccessed": "2026-03-20T06:30:14.979Z"
	},
	{
		"key": "ps_l",
		"value": "1",
		"domain": "facebook.com",
		"path": "/",
		"hostOnly": false,
		"creation": "2026-03-20T06:30:14.979Z",
		"lastAccessed": "2026-03-20T06:30:14.979Z"
	},
	{
		"key": "ps_n",
		"value": "1",
		"domain": "facebook.com",
		"path": "/",
		"hostOnly": false,
		"creation": "2026-03-20T06:30:14.979Z",
		"lastAccessed": "2026-03-20T06:30:14.979Z"
	},
	{
		"key": "locale",
		"value": "en_US",
		"domain": "facebook.com",
		"path": "/",
		"hostOnly": false,
		"creation": "2026-03-20T06:30:14.979Z",
		"lastAccessed": "2026-03-20T06:30:14.979Z"
	},
	{
		"key": "vpd",
		"value": "v1%3B694x360x2.698957920074463",
		"domain": "facebook.com",
		"path": "/",
		"hostOnly": false,
		"creation": "2026-03-20T06:30:14.979Z",
		"lastAccessed": "2026-03-20T06:30:14.979Z"
	},
	{
		"key": "pas",
		"value": "61588112155761%3AmVXTq0aTWb%2C61588342577468%3As9wrHbSTIv",
		"domain": "facebook.com",
		"path": "/",
		"hostOnly": false,
		"creation": "2026-03-20T06:30:14.979Z",
		"lastAccessed": "2026-03-20T06:30:14.979Z"
	},
	{
		"key": "m_pixel_ratio",
		"value": "2.698957920074463",
		"domain": "facebook.com",
		"path": "/",
		"hostOnly": false,
		"creation": "2026-03-20T06:30:14.979Z",
		"lastAccessed": "2026-03-20T06:30:14.979Z"
	},
	{
		"key": "wd",
		"value": "360x800",
		"domain": "facebook.com",
		"path": "/",
		"hostOnly": false,
		"creation": "2026-03-20T06:30:14.979Z",
		"lastAccessed": "2026-03-20T06:30:14.979Z"
	},
	{
		"key": "c_user",
		"value": "61588342577468",
		"domain": "facebook.com",
		"path": "/",
		"hostOnly": false,
		"creation": "2026-03-20T06:30:14.979Z",
		"lastAccessed": "2026-03-20T06:30:14.979Z"
	},
	{
		"key": "xs",
		"value": "24%3A2nN7214HUgjaYQ%3A2%3A1773988190%3A-1%3A-1",
		"domain": "facebook.com",
		"path": "/",
		"hostOnly": false,
		"creation": "2026-03-20T06:30:14.979Z",
		"lastAccessed": "2026-03-20T06:30:14.979Z"
	},
	{
		"key": "fr",
		"value": "0EYJ7KQ9y83NGcQpn.AWcuBR5HSxndSlv05xVcHL7fx9rrJleCNqfKubdd-_3ZFDuj5gY.BpvCPv..AAA.0.0.BpvOlk.AWeYSW2jWmZouK9umyLyFLLfCy4",
		"domain": "facebook.com",
		"path": "/",
		"hostOnly": false,
		"creation": "2026-03-20T06:30:14.979Z",
		"lastAccessed": "2026-03-20T06:30:14.979Z"
	},
	{
		"key": "fbl_st",
		"value": "101736722%3BT%3A29566469",
		"domain": "facebook.com",
		"path": "/",
		"hostOnly": false,
		"creation": "2026-03-20T06:30:14.979Z",
		"lastAccessed": "2026-03-20T06:30:14.979Z"
	},
	{
		"key": "wl_cbv",
		"value": "v2%3Bclient_version%3A3114%3Btimestamp%3A1773988196",
		"domain": "facebook.com",
		"path": "/",
		"hostOnly": false,
		"creation": "2026-03-20T06:30:14.979Z",
		"lastAccessed": "2026-03-20T06:30:14.979Z"
	}
]
